name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
	cd submissiontool
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Change directory and Run Tests
      run: |
	cd submissiontool
        python manage.py test
